# Nuclio Debugger

name: CI Nuclio

on:
  push:
    branches: [ main ]

jobs:
  nuclio-container:
    name: Nulcio Container
    runs-on: ubuntu-latest
    container:
      image: quay.io/nuclio/dashboard:1.5.16-amd64
      volumes:
        - /tmp:/tmp
        - /var/run/docker.sock:/var/run/docker.sock
      env:
        no_proxy: 172.28.0.1,${no_proxy}
        NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: 'true'
        NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE: 'volume'
      ports:
        - '8070:8070'
    steps:
      - name: Echo inside
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."  

